import "./globals.css";
import "aos/dist/aos.css"
import "bootstrap/dist/css/bootstrap.min.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export const metadata = {
  title: "Cybexonics ITConsultants",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
	  <Navbar />
    <div className="mt-5">
	  {children}
    </div>
	  <Footer />
    
	  </body>
    </html>
  );
}
